services:

  devcontainer:
    build:
      context: .
      dockerfile: rust.Dockerfile
      args:
        - RUST_VERSION=1.74.0
        - USER_NAME=k33g
    volumes:
      - ../..:/workspaces:cached      
    environment:
      - MESSAGE="Hello World!"
    command: sleep infinity
